server:
  port: 8989
spring:
  application:
    name: gateway
  cloud:
    consul:
      port: 8500
      host: 127.0.0.1
      discovery:
        service-name: ${spring.application.name}
    gateway:
      routes:
        - id: user_route
          uri: lb://users
          predicates:
            - Path=/feign/**
        - id: product_route
          uri: lb://products
          predicates:
            - Path=/product/**
            - Cookie=username,zq
          filters:
            - AddRequestParameter=id,23
      discovery:
        locator:
          enabled: true